<?php
// Gaming World 2006 <https://gamingw.net/>
// © MIT License

global $emoticon_sets, $emoticon_sets_info, $emoticon_basepath;

// A reference to all our emoticons. This gets populated on initialization.
$emoticon_sets = null;
$emoticon_sets_info = null;
// The base path where all emoticons are located, from the theme directory.
$emoticon_basepath = '/images/__gwnew/emoticons';

/**
 * Returns the base URL where the smileys are stored.
 */
function get_emoticons_base_url() {
  global $modSettings, $context;
  return implode('/', [$modSettings['smileys_url'], $context['smiley_set']]);
}

/**
 * Returns the GW2006 emoticon data.
 * 
 * If all is well, the actual emoticons in the database were based on this data,
 * inserted through the SQL generated by util/gen_emoticons_sql.php.
 */
function get_gw_emoticons_data() {
  global $settings;
  return json_decode(file_get_contents("{$settings['theme_dir']}/images/__gwnew/emoticons/info.json"), true);
}

/**
 * Returns metadata for emoticons.
 * 
 * This will pull data from both the database (if available on the page) and the emoticons data file.
 * 
 * Hidden emoticons are skipped entirely.
 */
function get_emoticons_metadata() {
  global $context, $modSettings;

  $base_url = get_emoticons_base_url();
  $gw_data = get_gw_emoticons_data();
  $gw_sets = [];
  $gw_emoticons = [];

  foreach ($gw_data['sets'] as $set) {
    $gw_sets[$set['name']] = [
      'name' => $set['name'],
      'title' => $set['title']
    ];
    for ($n = 0; $n < count($set['items']); ++$n) {
      $emoticon = $set['items'][$n];
      $gw_emoticons[$emoticon['filename']] = $emoticon;
      $gw_emoticons[$emoticon['filename']]['_n'] = $n;
    }
  }

  // Generate the final version of the metadata by combining SMF smiley data with GW data.
  // The SMF smiley data is not always available, so only add it if it is.
  $emoticon_metadata = [];

  foreach ($context['smileys'] as $type => $type_rows) {
    foreach ($type_rows as $n => $row) {
      for ($n = 0; $n < count($row['smileys']); ++$n) {
        $smiley = $row['smileys'][$n];
        if (!isset($emoticon_metadata[$smiley['filename']])) {
          $emoticon_metadata[$smiley['filename']] = $smiley;
          $emoticon_metadata[$smiley['filename']]['_primary_code'] = $emoticon_metadata[$smiley['filename']]['code'];
          $emoticon_metadata[$smiley['filename']]['code'] = [];
          $emoticon_metadata[$smiley['filename']]['_n'] = $n;
          $emoticon_metadata[$smiley['filename']]['_location'] = $type;
          $emoticon_metadata[$smiley['filename']]['_hidden'] = false;
        }
        $emoticon_metadata[$smiley['filename']]['code'][] = $smiley['code'];
      }
    }
  }

  foreach ($gw_emoticons as $filename => $data) {
    if ($data['hidden']) {
      continue;
    }
    if (!isset($emoticon_metadata[$filename])) {
      $emoticon_metadata[$filename] = $data;
    }
    $emoticon_metadata[$filename]['size'] = $data['size'];
    $emoticon_metadata[$filename]['_primary_code'] = $data['code'][0];
    $emoticon_metadata[$filename]['_location'] = $data['location'];
    $emoticon_metadata[$filename]['_hidden'] = $data['hidden'];
  }

  foreach ($emoticon_metadata as $filename => $data) {
    $emoticon_metadata[$filename]['_url'] = implode('/', [$modSettings['smileys_url'], $context['user']['smiley_set'], $filename]);
  }
  
  return ['sets' => $gw_sets, 'emoticons' => $emoticon_metadata];
}
